### ISSUE TITLE
please include the LICENSE file in published compose_spec_macros crates

### ISSUE THREAD

**Issue by decathorpe** [k9withabone/compose_spec_rs#21]
The MPL-2.0 license requires that a copy of the license text is included with (re-)distributed sources. The separately published compose_spec_macros crate currently doesn't contain the license text.

I'm working on packaging this crate for Fedora Linux as a dependency of [podlet](https://github.com/containers/podlet), and not having the license file included requires awkward workarounds for us (and technically you and crates.io are violating your own license terms by redistributing the source code without accompanying license text via crates.io).

**Comment by k9withabone** [comment]
Oops, sorry about that. This was my first published project using cargo workspaces. Would adding a symlink to the `LICENSE` file in the `compose_spec_macros` directory work for your purposes?

**Comment by decathorpe** [comment]
Yes, adding a symbolic link is enough so long as you run `cargo publish` on any operating system that supports symbolic links (i.e. not Windows). Thank you for looking into it!

**Comment by decathorpe** [comment]
Thank you!
